trigger:
- main  # your branch
 
pool:
  name: 'devopsagent-1'   # replace with your managed agent pool name
 
variables:
  azureSubscription: 'ARM-conn'       # DevOps service connection
  aksResourceGroup: 'nayana'
  aksCluster: 'aks-managed-dev'
 
stages:
- stage: Deploy
  displayName: 'Deploy NGINX to AKS'
  jobs:
  - job: Deploy
    displayName: 'Deploy Test App'
    steps:
    # Step 1: Show managed agent public IP
    - script: |
        echo "Detecting outbound public IP..."
        curl -s https://ifconfig.me
      displayName: "Show outbound public IP"
 
    # Step 2: Deploy to AKS
    - task: Kubernetes@1
      displayName: 'Deploy to AKS'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscription)
        azureResourceGroup: $(aksResourceGroup)
        kubernetesCluster: $(aksCluster)
        command: 'apply'
        useConfigurationFile: true
        configuration: 'manifests/deployment.yaml'