trigger: 
- main

variables:
  dockerRegistryServiceConnection: '467aebc6-c2d7-48d1-af79-d79a67c80398'
  imageRepository: 'aks-test-app'
  containerRegistry: 'myzomato'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

  azureSubscription: 'default'
  azureResourceGroup: 'Nayana'
  kubernetesCluster: 'mangedevopsagent'
  namespace: 'prod'

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      name: magedpool
    steps:
    # Step 1: Install Docker
    - script: |
        echo "Installing Docker on managed agent..."
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common gnupg-agent
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        sudo systemctl start docker
        sudo systemctl enable docker
        docker --version
      displayName: Install Docker

    # Step 2: Build & Push Docker Image
    - task: Docker@2
      displayName: Build and Push Docker image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy Job
    environment: 'aks-test'
    pool:
      name: magedpool
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@1
            displayName: Apply Deployment YAML
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: $(azureSubscription)
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              namespace: $(namespace)
              command: 'apply'
              useConfigurationFile: true
              configuration: 'manifests/deployment.yaml'

          - task: Kubernetes@1
            displayName: Update Image Tag
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: $(azureSubscription)
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              namespace: $(namespace)
              command: 'set'
              arguments: "image deployment/aks-test-deploy aks-test-container=$(containerRegistry)/$(imageRepository):$(tag)"
