trigger:
- main  # your branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'default'       # DevOps service connection
  aksResourceGroup: 'nayana'
  aksCluster: 'managedevopsagent'

stages:
- stage: Deploy
  displayName: 'Deploy NGINX to AKS'
  jobs:
  - job: Deploy
    displayName: 'Deploy Test App'
    steps:
    - task: Kubernetes@1
      displayName: 'Deploy to AKS'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscription)
        azureResourceGroup: $(aksResourceGroup)
        kubernetesCluster: $(aksCluster)
        command: 'apply'
        useConfigurationFile: true
        configuration: 'manifests/deployment.yaml'
