apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:                      # <-- resources go under spec of the pod, inside container
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:            # <-- correct place
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx-svc
spec:
  type: LoadBalancer
  selector:
    app: test-nginx
  ports:
    - port: 80
      targetPort: 80
